--- #구분
spring:
    profiles:
        include: google
    mustache:
        suffix: .html
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
        properties:
            strategy: org.hibernate.dialect.MySQL5InnoDBDialect
    session:
        store-type: jdbc
    logging:
        level:
            org.springframework: info
        pattern:
            console: "%d{yyyy-MM-dd HH:mm:ss} [%X{visitorIp}] [%thread] %-5level %logger{36} – %msg%n"

--- #구분
spring:
    profiles: local
    h2:
        console:
            enabled: true
    mustache:
        cache: false
        prefix: file:///C:\Users\nelld\IdeaProjects\springboot2-webservice\src\main\resources\templates\
    resources:
        static-locations: file:///C:\Users\nelld\IdeaProjects\springboot2-webservice\src\main\resources\static\