--- #구분
spring:
    profiles:
        include: google
    mustache:
        suffix: .html
    jpa:
        show-sql: true
        properties:
            strategy: org.hibernate.dialect.MySQL5InnoDBDialect
    session:
        store-type: jdbc
--- #구분
spring:
    profiles:
        active: local
    h2:
        console:
            enabled: true
    mustache:
        cache: false
        prefix: file:///C:\Users\nelld\IdeaProjects\springboot2-webservice\src\main\resources\templates\
    resources:
        static-locations: file:///C:\Users\nelld\IdeaProjects\springboot2-webservice\src\main\resources\static\